language: node_js
node_js:
- '8'
script: yarn build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIZ72Q3NBHAQH3LHA
  secret_access_key:
    secure: JrRdb0TrMBZLCJP3CdUIZb8KueStsRX+W2lwlxEuFAk3vZ/+IntmH0fXesiSxiqF7zmj9mr/Q3gmim6VPXE27QuFYzx7HCKkogzzh3yi1POKog7HWYFNTFUnFLQr8ZNADSF6iCfv1OXTaSkLLLmh/nVP/U3KkGUDvfaao3jUyT/ceupw9QtNw+HgXbMmiV1BvAyJnQRRnDCnMCachGCWQSVADycZnP+xKn/5F/6BT+7VbQp0FiEMJyOKPVLK3Lhnhzkwmej9movAe+/quNTUBaFfxw5CZWhSCx+CvyOOuft2Oe1b2DX4bkaDeF6IOlDNPu1UBN8AY58RNnHsym+/tTKkmWFnWg9TlgnEzdclx4XbarewsiCMteLQ/wY5xBmu+/2Dj492iWs/CMOcfb2DPM90QvHJCFDXAF/AJruKBWWVYRirjbpwIKxEQUpjim18ezo1TDGZhhLWt5u45tXnXgXtSlf+O582FNai8+SHGAbv61jdwVCzxNZO+Dq6fYmXtvoOj31TsLvQto+WX6uy44YyTfjv5mnoEu7yR0aInxS6Exj01VlyL6FkUZW6GwrQVqTp0Led7OWo2v6GO8FVl4VNG3+6DmFF2AtjSKQoELQJDj5hKihueBiDJCCgkPYQtaN1TH+uCeonIigMPhaF8TKsp9eH9O6lKZ/wZAVDM9w=
  bucket: hgogonis.me
  local-dir: public
  region: us-west-2
  on:
    repo: HarryGogonis/portfolio
