language: node_js
node_js:
- '8'
script: yarn build
deploy:
  skip_cleanup: true
  acl: public-read
  provider: gcs
  access_key_id: GOOGW6R6IS4CV6K32GHA
  secret_access_key:
    secure: NBFM5ZFZVa2K06k6JG6b/5lIbqWSR4BbYMnkrj0yA6maWWheV9DtsJOmm6ZWdylZm3s2vqbIMhV+Mr526vk1peIXw3QvEa9Tto/DYshKqp/XKBvEqIzWEtF68zj8w9zlC9Zi2r725TpgjIW32mheqNM+pPrufdCyh1y2OlExtqWTbY2Ow+Ajg1EVvGi4kGcBKg/UZ4uUZtwKLTHtVsRKBpr3jwcQcLz9LZvg/R5bfJQyUVGtvbap7P8Q+/HZDJ30sAEN+9fnArTVyZd2WacjQ7mRy/Oui8dm5HUnfF9qhylZflTwmausGzs+4Sfa/z79kMyIsPMvrxbFA5RfPs8lAYPi6t3yAQ1rMkEzKGDytMmU9eLQu7vLOxhb43RWf6M0fG+zKQVbcVWG3EUiEO0vet8ppLssXT7t4W5KB/RMJYvUYf696bHa98RiYAMMC+sE9RWbMBZPpyiZQlhvM8fV6G0BxXdIYfxJqRWvkn3DrDMo6QaPLGKskCdbn9DGgkIU4oTS6qDODsJjl5G2zWJ4Q+5u5iOB8BS89zry87M96wl4S0u5NMNCCfIMb50Y6ZSFKCgnma+mUeukobI/mabcKERPyYconJ0yUNbm6LjEoV+YD71Jr0b8pbv8g8LdeFVSb7tOBy8nRr6Mp+r504s+8ZNkrxCalTQpApevNUICmb0=
  bucket: hgogonis.me
  local-dir: public
  on:
    repo: HarryGogonis/portfolio
