siteTitle = "Blog by Harry Gogonis"
siteDescr = "Software Engineer / React/ Redux"
siteAuthor = "Harry Gogonis"

siteTwitterUrl = "https://twitter.com/HarryGogonis"
siteGithubUrl = "https://github.com/HarryGogonis"

googleAnalyticsId = "UA-104743371-1"

linkPrefix = "/gatsby-starter-lumen"
