siteTitle = "Harry Gogonis"
siteDescr = "Software Engineer / React / Redux"
siteAuthor = "Harry Gogonis"
siteUrl = "http://hgogonis.me"

siteTwitterHandle = "HarryGogonis"
siteGithubUrl = "https://github.com/HarryGogonis"
siteLinkedInUrl = "https://www.linkedin.com/in/harrygogonis/"

googleAnalyticsId = "UA-104743371-1"

linkPrefix = "/gatsby-starter-lumen"
